### ISSUE TITLE
ak.to_numpy(ak.Array([[], [], []])) should return an array of shape (3, 0), not (0, 0)

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#1048]
### Version of Awkward Array

HEAD

### Description and code to reproduce

```python
>>> ak.to_numpy(ak.Array([[], [], []]))   # should have shape (3, 0)
array([], shape=(0, 0), dtype=float64)
```

It's probably not setting the `zeros_length` argument when converting the ListArray or ListOffsetArray into a RegularArray. It's possible to express such an array:

```python
>>> shape30 = ak.Array(ak.layout.RegularArray(
...     ak.layout.NumpyArray(np.array([])),
...     size=0,
...     zeros_length=3,
... ))
>>> shape30
<Array [[], [], []] type='3 * 0 * float64'>
```

... or maybe the outer length is being lost _later_ in the process, because look at this:

```python
>>> ak.to_numpy(shape30)
array([], shape=(0, 0), dtype=float64)
```

Anyway, it's probably an easy fix, once we know where the outer length is being lost.

**Comment by ianna** [comment]
@jpivarski - I wanted to check if this is still the case in v2 and stumbled an another issue with `EmptyArray`s in v2 (fixed in https://github.com/scikit-hep/awkward-1.0/pull/1150/commits/54c55cd8ab2bf7890823527a7f15023463b1c3bf):
```python
>>> array = ak._v2.highlevel.Array([[], [], []])
>>> ak.to_list(array.layout.toRegularArray())
[[], [], [], []]
>>> array = ak._v2.highlevel.Array([[1], [2], [3]])
>>> ak.to_list(array.layout.toRegularArray())
[[1], [2], [3]]
>>> array = ak.Array([[], [], []])
>>> ak.to_list(array.layout.toRegularArray())
[[], [], []]
```

**Comment by jpivarski** [comment]
For more detail, here's where `ListOffsetArray.toRegularArray` is going wrong:

```python
>>> array = ak._v2.highlevel.Array([[], [], []])
>>> array.layout
<ListOffsetArray len='3'>
    <offsets><Index dtype='int64' len='4'>[0 0 0 0]</Index></offsets>
    <content><EmptyArray len='0'/></content>
</ListOffsetArray>
>>> array.layout.toRegularArray()
<RegularArray size='0' len='4'>
    <content><EmptyArray len='0'/></content>
</RegularArray>
```

The length of the ListOffsetArray is 3, but the length of the RegularArray is 4.

Here's the new Python code with the error:

https://github.com/scikit-hep/awkward-1.0/blob/7705900c44db2ced202ae61ce605f9d7ea536f4a/src/awkward/_v2/contents/listoffsetarray.py#L159-L165

The length of the RegularArray that gets returned should be `len(self)` or `len(self._offsets) - 1` (because offsets are one longer than the ListOffsetArray itself).

Here's the original C++ code that it was translated from:

https://github.com/scikit-hep/awkward-1.0/blob/7705900c44db2ced202ae61ce605f9d7ea536f4a/src/libawkward/array/ListOffsetArray.cpp#L383-L387

This uses `length()`, a function that doesn't exist in the Python version but means `len(self)`. That's how the error was made.

@ianna Are you working on something where it would be easy to include this fix, or should I?

**Comment by jpivarski** [comment]
@ianna You already fixed it in #1150 (which I'm reviewing right now). Exactly this fix is included in the diff.

We should keep this issue here because it was for a different problem, the `to_numpy` shape issue. (Or is that handled by #1150? I'll check. Nope; the issue is still there in `ianna/to_numpy`, at the time of writing.)
