### ISSUE TITLE
Writing a non-minimal categorical/dictionary to Parquet corrupts it

### ISSUE THREAD

**Issue by jpivarski** [scikit-hep/awkward#400]
Moving @drahnreb's comment to a new issue, because it's unrelated to Parquet file partitioning. Original text below:

I found a rather weird behaviour that seems to be linked to partitioned parquets and my suggested "workaround".
> ```python
> # current workaround with pq directly
> table = pq.read_table(parquet_dir)
> ak.from_arrow(table)
> ```

As this is not a supported feature, I did not want to open a bug report but figured it's worth sharing as it took me a while to figure out that the above seems to cause the following issue.
Previously loaded partitioned data and slicing it (on a low level) will result in a `ValueError: in IndexedArray32 attempting to get xxx, index[i] >= len(content)` when saving to parquet and reloading.

Working Example:
A bit more extensive that explains the principles of what I am trying to achieve, as I realized the combination of certain aspects matter esp. details about the containing dtypes and conversions.
I couldn't figure out what is happening. I first suspected wrong advanced slicing (#370) or the type conversion awk-parquet-arrow as described [here](https://awkward-array.org/how-to-convert-arrow.html) or (#393).
It was difficult to reproduce the results - so it might not be really a minimal example. Sorry for that!

```python
# let's create some fake data that will be saved as parquet
df = pd.DataFrame([{"id": n, "label": np.random.choice(["OK", "NOK"], 1)[0], "year": np.random.choice([2019, 2020], 1), "arr": np.random.rand(np.random.randint(0,100))} for n in range(10000)])
# cast label
df.label = df.label.astype("category")
df.year = df.year.astype("uint32")
# index
df.set_index(['id'], inplace=True)
# save as partioned parquet
df.to_parquet('test.parquet',
              partition_cols=['year'], # this seems to be crucial
              version='2.0',
              data_page_version='2.0')
# let's get started. reload
table = pq.read_table('t.parquet')
# load as awkward array
original = ak.from_arrow(table)
```
```python
>>> original.layout
<RecordArray>
    <field index="0" key="label">
        <IndexedArray64>
            <index><Index64 i="[0 0 0 1 0 ... 19 19 19 18 18]" offset="0" length="20026" at="0x55d32435ff10"/></index>
            <content><ListArray64>
                <parameters>
                    <param key="__array__">"string"</param>
                </parameters>
                <starts><Index64 i="[0 3 5 8 10 ... 38 40 43 45 48]" offset="0" length="20" at="0x55d31bdf77d0"/></starts>
                <stops><Index64 i="[3 5 8 10 13 ... 40 43 45 48 50]" offset="0" length="20" at="0x55d31be3ff70"/></stops>
                <content><NumpyArray format="B" shape="50" data="78 79 75 79 75 ... 78 79 75 79 75" at="0x55d30a4851b0">
                    <parameters>
                        <param key="__array__">"char"</param>
                    </parameters>
                </NumpyArray></content>
            </ListArray64></content>
        </IndexedArray64>
    </field>
    <field index="1" key="arr">
        <ListArray64>
            <starts><Index64 i="[0 26 46 54 81 ... 995057 995093 995152 995214 995284]" offset="0" length="20026" at="0x55d3243870f0"/></starts>
            <stops><Index64 i="[26 46 54 81 150 ... 995093 995152 995214 995284 995357]" offset="0" length="20026" at="0x55d3243ae2d0"/></stops>
            <content><IndexedOptionArray64>
                <index><Index64 i="[0 1 2 3 4 ... 995352 995353 995354 995355 995356]" offset="0" length="995357" at="0x55d328748590"/></index>
                <content><NumpyArray format="f" shape="995357" data="0.726096 0.590173 0.699854 0.116417 0.743831 ... 0.0755084 0.756987 0.240388 0.158446 0.722705" at="0x55d312824ab0"/></content>
            </IndexedOptionArray64></content>
        </ListArray64>
    </field>
    <field index="2" key="id">
        <IndexedOptionArray64>
            <index><Index64 i="[0 1 2 3 4 ... 20021 20022 20023 20024 20025]" offset="0" length="20026" at="0x55d3243d54b0"/></index>
            <content><NumpyArray format="l" shape="20026" data="2 3 4 8 9 ... 9984 9987 9992 9996 9998" at="0x55d312bf0b30"/></content>
        </IndexedOptionArray64>
    </field>
    <field index="3" key="year">
        <NumpyArray format="i" shape="20026" data="2019 2019 2019 2019 2019 ... 2020 2020 2020 2020 2020" at="0x55d3233b27b0"/>
    </field>
</RecordArray>
```
Main focus is on the field `label` with a `ListArray64` that is nested in `IndexedArray64`.

Let's now mask the array and slice based on indices within each variable length array.
```python
# might be irrelevant
remove = np.random.choice([False, True], size=len(original))
masked = original[~remove].copy()
# "materialize"
masked = ak.flatten(masked, axis=0)
# slice nested arrays based on #370 (unofficial slicing)
starts = np.asarray(masked.arr.layout.starts).astype("uint64")
stops = np.asarray(masked.arr.layout.stops).astype("uint64")
# gather plausible indices with intrinsic information (here randomized)
def _get_each_idx(starts, stops):
    diffs = stops-starts
    nzd = diffs[np.where(diffs > 0)[0]]
    rs = np.random.randint(np.zeros(len(nzd)).astype(int), nzd)
    diffs[np.where(diffs != 0)[0]] = rs
    return diffs.astype("uint64")
# set  new stops and starts
start_idx = _get_each_idx(starts, stops)
new_starts = start_idx + starts
end_idx = _get_each_idx(new_starts, stops)
new_stops = end_idx + new_starts
# change nested arrays (based on unofficial lowlevel layout)
layout = masked.layout
fields = []
for k in layout.keys():
    if not k in ['arr']:
        fields.append(layout[k])
    else:
        fields.append(ak.layout.ListArray64(
            ak.layout.Index64(starts_n),
            ak.layout.Index64(stops_n),
            layout[k].content
            )
        )

# main result. reconstruct back to a RecordArray.   
sliced = ak.layout.RecordArray(
        fields,
        layout.keys()
    )
```
While this is a low level composing of arrays it provides consistent arrays and works until the result is exported as parquet.
```python
>>> ak.is_valid(original), ak.validity_error(original), ak.is_valid(masked), ak.validity_error(masked), ak.is_valid(sliced), ak.validity_error(sliced)
(True, None, True, None, True, None)
```

The problem starts when reloading data.
```python
>>> sliced_arr = ak.Array(sliced)
>>> sliced_arr = ak.flatten(sliced_arr, axis=0)
>>> ak.to_parquet(sliced_arr, "tmp.parquet")

>>> loaded = ak.from_parquet("tmp.parquet")
>>> loaded
<Array [{label: 'NOK', arr: [, ... year: 2020}] type='10054 * {"label": string, ...'>
>>> ak.is_valid(loaded), ak.validity_error(loaded)
(False,
 'at layout.field(0) (IndexedArray32): index[i] >= len(content) at i=4936')
```

Jagged arrays can be accessed along the entire axis.
```python
>>> sliced_arr.arr[10000]
<Array [0.982, 0.695, 0.111, ... 0.637, 0.984] type='77 * ?float32'>
>>> sliced_arr.label[10000]
'NOK'
>>> loaded.arr[10000]
<Array [0.982, 0.695, 0.111, ... 0.637, 0.984] type='77 * ?float32'>
```

... `label` field will throw a ValueError: in IndexedArray32 attempting to get 4936, index[i] >= len(content)
```python
for i in range(len(loaded)):
    try:
        loaded[i, 'label'].tolist()
    except ValueError:        
        print(i)
        pass
```

@jpivarski

_Originally posted by @drahnreb in https://github.com/scikit-hep/awkward-1.0/issues/368#issuecomment-676286664_

**Comment by jpivarski** [comment]
Thanks for reporting this issue, though I have to complain a bit about the reproducer: the relevant part is between the `sliced_arr`, which is valid, and the `loaded`, which is not. Building arrays from handmade layouts is supported (it's part of the public API), but it's exactly the sort of thing that leads to validity errors.

However, in this case it really is a bug: there's an error in the writing of non-minimal categorical/dictionary data (what Awkward calls [IndexedArrays](https://awkward-array.readthedocs.io/en/latest/ak.layout.IndexedArray.html)) to Parquet. Actually, I think it's a pyarrow bug and I'll be reporting it on their JIRA right after this.

Your `label` is a categorical variable. Perhaps because it was loaded from partitioned data, the labels are not minimal: `"OK"` and `"NOK"` are the unique values, so only two are strictly needed, but the array has about ten of them. That's not wrong, just less efficient, and not much more inefficient (though if you're using the integers for equality checks, which one typically does with categorical data, but Awkward doesn't, then it would be wrong).

Here's a small example:

```python
>>> import awkward1 as ak
>>> import numpy as np
>>> categories = ak.Array(["one", "two", "three", "one", "two", "three"])
>>> index = ak.layout.Index32(np.array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], np.int32))
>>> indexedarray = ak.layout.IndexedArray32(index, categories.layout)
>>> original = ak.Array(indexedarray)
>>> original
<Array ['one', 'two', ... 'two', 'three'] type='12 * string'>
>>> original.tolist()
['one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three']
```

It's non-minimal because we could have represented this with just three categories and an `index` of values in `[0, 3)`. This converts to and from Arrow without any problems:

```python
>>> roundtrip = ak.from_arrow(ak.to_arrow(original))
>>> roundtrip.tolist()
['one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three', 'one', 'two', 'three']

>>> original.layout
<IndexedArray32>
    <index><Index32 i="[0 1 2 3 4 ... 1 2 3 4 5]" offset="0" length="12" at="0x55edccd57930"/></index>
    <content><ListOffsetArray64>
        <parameters>
            <param key="__array__">"string"</param>
        </parameters>
        <offsets><Index64 i="[0 3 6 11 14 17 22]" offset="0" length="7" at="0x55edccdae190"/></offsets>
        <content><NumpyArray format="B" shape="22" data="111 110 101 116 119 ... 116 104 114 101 101" at="0x55edccd3ded0">
            <parameters>
                <param key="__array__">"char"</param>
            </parameters>
        </NumpyArray></content>
    </ListOffsetArray64></content>
</IndexedArray32>

>>> roundtrip.layout
<IndexedArray32>
    <index><Index32 i="[0 1 2 3 4 ... 1 2 3 4 5]" offset="0" length="12" at="0x55edccd57930"/></index>
    <content><ListOffsetArray32>
        <parameters>
            <param key="__array__">"string"</param>
        </parameters>
        <offsets><Index32 i="[0 3 6 11 14 17 22]" offset="0" length="7" at="0x55edccdc8e60"/></offsets>
        <content><NumpyArray format="B" shape="22" data="111 110 101 116 119 ... 116 104 114 101 101" at="0x55edccd3ded0">
            <parameters>
                <param key="__array__">"char"</param>
            </parameters>
        </NumpyArray></content>
    </ListOffsetArray32></content>
</IndexedArray32>
>>> np.asarray(original.layout.index)

array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int32)
>>> ak.to_list(original.layout.content)
['one', 'two', 'three', 'one', 'two', 'three']

>>> np.asarray(roundtrip.layout.index)
array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5], dtype=int32)
>>> ak.to_list(roundtrip.layout.content)
['one', 'two', 'three', 'one', 'two', 'three']
```

However, when pyarrow writes it to Parquet (using the output of `ak.to_arrow`), it correctly minimizes the set of categories but garbles the index (probably some interaction with Parquet's very weird "definition levels" and "repetition levels"):

```python
>>> ak.to_parquet(original, "tmp.parquet")
>>> loaded = ak.from_parquet("tmp.parquet")
>>> loaded.layout
<IndexedArray32>
    <index><Index32 i="[0 1 2 3 0 ... 1 2 3 0 1]" offset="0" length="12" at="0x7f25a7e00280"/></index>
    <content><ListOffsetArray32>
        <parameters>
            <param key="__array__">"string"</param>
        </parameters>
        <offsets><Index32 i="[0 3 6 11]" offset="0" length="4" at="0x7f25a7e00240"/></offsets>
        <content><NumpyArray format="B" shape="11" data="111 110 101 116 119 ... 116 104 114 101 101" at="0x7f25a7e002c0">
            <parameters>
                <param key="__array__">"char"</param>
            </parameters>
        </NumpyArray></content>
    </ListOffsetArray32></content>
</IndexedArray32>
>>> np.asarray(loaded.layout.index)
array([0, 1, 2, 3, 0, 1, 1, 1, 2, 3, 0, 1], dtype=int32)    # <---- BAD!
>>> ak.to_list(loaded.layout.content)
['one', 'two', 'three']
```

The `index` ought to be `[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]`. Even pyarrow, by itself, doesn't like it:

```python
>>> import pyarrow.parquet
>>> table = pyarrow.parquet.read_table("tmp.parquet")
>>> table
pyarrow.Table
: dictionary<values=string, indices=int32, ordered=0>
>>> table.to_pydict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/table.pxi", line 1587, in pyarrow.lib.Table.to_pydict
  File "pyarrow/table.pxi", line 405, in pyarrow.lib.ChunkedArray.to_pylist
  File "pyarrow/array.pxi", line 1144, in pyarrow.lib.Array.to_pylist
  File "pyarrow/scalar.pxi", line 712, in pyarrow.lib.DictionaryScalar.as_py
  File "pyarrow/scalar.pxi", line 701, in pyarrow.lib.DictionaryScalar.value.__get__
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 111, in pyarrow.lib.check_status
pyarrow.lib.ArrowIndexError: tried to refer to element 3 but array is only 3 long
```

In fact, it's possible to cause this error without using Awkward, just pyarrow (something I'll have to do to report it on the Apache Arrow JIRA).

```python
>>> import pyarrow as pa
>>> import pyarrow.parquet
>>> pa_array = pa.DictionaryArray.from_arrays(
...     pa.array([0, 1, 2, 3, 4, 5, 0, 1, 2, 3, 4, 5]),
...     pa.array(["one", "two", "three", "one", "two", "three"])
... )
>>> pa_array
<pyarrow.lib.DictionaryArray object at 0x7f271befa4a0>

-- dictionary:
  [
    "one",
    "two",
    "three",
    "one",
    "two",
    "three"
  ]
-- indices:
  [
    0,
    1,
    2,
    3,
    4,
    5,
    0,
    1,
    2,
    3,
    4,
    5
  ]
>>> pa_table = pa.Table.from_batches(
...     [pa.RecordBatch.from_arrays([pa_array], ["column"])]
... )
>>> pa_table
pyarrow.Table
column: dictionary<values=string, indices=int64, ordered=0>
>>> pyarrow.parquet.write_table(pa_table, "tmp2.parquet")
>>> pa_loaded = pyarrow.parquet.read_table("tmp2.parquet")
>>> pa_loaded
pyarrow.Table
column: dictionary<values=string, indices=int32, ordered=0>
>>> pa_loaded.to_pydict()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pyarrow/table.pxi", line 1587, in pyarrow.lib.Table.to_pydict
  File "pyarrow/table.pxi", line 405, in pyarrow.lib.ChunkedArray.to_pylist
  File "pyarrow/array.pxi", line 1144, in pyarrow.lib.Array.to_pylist
  File "pyarrow/scalar.pxi", line 712, in pyarrow.lib.DictionaryScalar.as_py
  File "pyarrow/scalar.pxi", line 701, in pyarrow.lib.DictionaryScalar.value.__get__
  File "pyarrow/error.pxi", line 122, in pyarrow.lib.pyarrow_internal_check_status
  File "pyarrow/error.pxi", line 111, in pyarrow.lib.check_status
pyarrow.lib.ArrowIndexError: tried to refer to element 3 but array is only 3 long
>>> pa.__version__
'1.0.0'
```

So it's a pyarrow bug. (Even if they say that non-minimal dictionaries are not valid, it shouldn't silently write the wrong thing into a Parquet file.)

However, I think I'm going to do something about it on the Awkward side, anyway: we ought to have an explicit categorical type, just as we have a string type (as a high-level behavior on IndexedArray). Putting an IndexedArray into categorical form would mean minimizing it, and when it's minimized, we don't encounter the pyarrow bug. Conversion to Arrow and hence Parquet would turn minimized categoricals into Arrow/Parquet dictionaries and would flatten any other IndexedArray.

I'll report updates on the pyarrow bug and Awkward categoricals here.

**Comment by drahnreb** [comment]
Thanks for moving it Jim.

I think it is writing _and reading_ as changing the partitioning (?) will reverse the effect.

Remove the partition here to:
```python
df.to_parquet('nonpartitioned.parquet',
              version='2.0',
              data_page_version='2.0')
original = ak.from_parquet('nonpartitioned.parquet')
# same for pyarrow table = pq.read_table('nonpartitioned.parquet')
...
```
will invalidate the manipulations for sliced:
```python
...
>>> ak.is_valid(sliced), ak.validity_error(sliced)
(False,
 'at layout.field(2) (ListArray64): stop[i] > len(content) at i=5040')
```

while 
```python
>>> ak.is_valid(loaded), ak.validity_error(loaded)
(True, None)
```

So maybe also low level slicing or subsequently `is_valid()` does not invalidate something in the first place?

**Comment by jpivarski** [comment]
I've reported this as [ARROW-9801](https://issues.apache.org/jira/browse/ARROW-9801). Meanwhile, I'll look into fixing things on our side so that we don't hit this, and gain "categorical" as a distinct thing from IndexedArray.

**Comment by jpivarski** [comment]
Labeled a "feature request" because this is not our bug. Specialized categorical data would be a new feature.

Nah, that's weird. The system (Awkward + Arrow) as it stands corrupts data. I should call it a bug. The categorical data type is motivated by making Parquet output not wrong. I'll label it as a bug.

**Comment by jpivarski** [comment]
This was accidentally closed before because I repurposed a PR to get some updates into a release. But it's really done now, in #403.

The fix involved creating a new high-level type: categorical. I had been saying that [IndexedArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.IndexedArray.html) nodes are equivalent to categorical data, but they don't guarantee that the their `content` (the categories) are unique, and uniqueness is important for some operations, as we've just seen. The categorical type is explicitly opt-in, since the uniqueness-construction can be expensive. (It scales as _n log(n)_, rather than _n_, and I implemented it with a tight Python loop that fills a dict, which is unusual—nearly everything else is in compiled loops. If this type is useful, it can be lowered into the compiled layer, but doing so for the general case would be a big project.)

You probably want your `"OK"`/`"NOK"` data to be categorical. The function for that is `ak.to_categorical` (check its help string; its documentation will be on the website after I push to master). If the speed of this function is an issue, you can build it manually, since you're comfortable using layouts:

```python
>>> import awkward1 as ak
>>> import numpy as np
>>> original = ak.Array(["OK", "OK", "NOK", "OK", "NOK", "OK", "NOK"])
>>> ak.is_categorical(original)
False
>>> original.layout
<ListOffsetArray64>
    <parameters>
        <param key="__array__">"string"</param>
    </parameters>
    <offsets><Index64 i="[0 2 4 7 9 12 14 17]" offset="0" length="8" at="0x557bbe332760"/></offsets>
    <content><NumpyArray format="B" shape="17" data="79 75 79 75 78 ... 79 75 78 79 75" at="0x557bbe2be9e0">
        <parameters>
            <param key="__array__">"char"</param>
        </parameters>
    </NumpyArray></content>
</ListOffsetArray64>
>>> categorical = ak.to_categorical(original)
>>> ak.is_categorical(categorical)
True
>>> ak.categories(categorical)
<Array ['OK', 'NOK'] type='2 * string'>
>>> categorical.layout
<IndexedArray64>
    <parameters>
        <param key="__array__">"categorical"</param>
    </parameters>
    <index><Index64 i="[0 0 1 0 1 0 1]" offset="0" length="7" at="0x557bbe2b0d80"/></index>
    <content><ListArray64>
        <parameters>
            <param key="__array__">"string"</param>
        </parameters>
        <starts><Index64 i="[0 4]" offset="0" length="2" at="0x557bbe2f59d0"/></starts>
        <stops><Index64 i="[2 7]" offset="0" length="2" at="0x557bbe2f5a10"/></stops>
        <content><NumpyArray format="B" shape="17" data="79 75 79 75 78 ... 79 75 78 79 75" at="0x557bbe2be9e0">
            <parameters>
                <param key="__array__">"char"</param>
            </parameters>
        </NumpyArray></content>
    </ListArray64></content>
</IndexedArray64>
>>> manual_categories = ak.Array(["OK", "NOK"]).layout
>>> manual_index = ak.layout.Index64(np.array([0, 0, 1, 0, 1, 0, 1], np.int64))
>>> manual_categorical = ak.layout.IndexedArray64(manual_index, manual_categories, parameters={"__array__": "categorical"})
>>> categorical2 = ak.Array(manual_categorical)
>>> categorical2
<Array ['OK', 'OK', 'NOK', ... 'OK', 'NOK'] type='7 * categorical[type=string]'>
>>> ak.is_categorical(categorical2)
True
>>> ak.categories(categorical2)
<Array ['OK', 'NOK'] type='2 * string'>
>>> ak.to_list(categorical2)
['OK', 'OK', 'NOK', 'OK', 'NOK', 'OK', 'NOK']
```

And if you know the categories explicitly, you can build the `manual_index` in a way that scales with _n_ and involves only compiled code:

```python
>>> manual_index_array = np.empty(len(original), dtype=np.int64)
>>> manual_index_array[original == "OK"] = 0
>>> manual_index_array[original == "NOK"] = 1
>>> manual_index_array
array([0, 0, 1, 0, 1, 0, 1])
```

The thing that this explicitness buys us is that Awkward ↔ Arrow conversion now has the following rule:

   * If the Awkward IndexedArray is _labeled as categorical_, then it maps to and from Arrow dictionary encoding—we have reason to believe that the categories are unique (we assume that they are constructed that way, which `ak.to_categorical` guarantees).
   * If the Awkward IndexedArray is not labeled as categorical, then it gets "evaluated" (`array → array.content[array.index]`) before conversion to Arrow.

As long as the Awkward categorical arrays really do have unique categories, we are insensitive to ARROW-9801, and you can use Parquet files freely.

Incidentally, I noticed that your data started as Pandas: if you're interested in writing `ak.from_pandas` (does not exist: [Pandas conversion is one-sided](https://awkward-array.org/how-to-convert-pandas.html)), then I could help you out with that. Now that we have a categorical type, we have something to convert categorical Pandas columns into. On my side, I need to enable datetime types and partitioned Parquet datasets, which would then cover a lot of ground.

**Comment by drahnreb** [comment]
This looks great! I will try it with a dataset shortly.

I'm interested in writing `ak.from_pandas`, kindly guide me through.

**Comment by drahnreb** [comment]
@jpivarski Jim, I opened a draft pull request according to contribution guideline. Would appreciate your advises, you should be able to edit the PR comment.

**Comment by jpivarski** [comment]
> I'm interested in writing `ak.from_pandas`, kindly guide me through.

Cool! The `ak.to_pandas` function is here:

https://github.com/scikit-hep/awkward-1.0/blob/83232704d7cd5770804f3ece75559cd3de59eaf3/src/awkward1/operations/convert.py#L3467-L3685

though some of the issues are different: Awkward → Pandas requires, in general, multiple DataFrames to be lossless, and so there's a lot of logic there to determine which DataFrame each column should go in to make a minimal set of DataFrames. For Pandas → Awkward, only one DataFrame is ever involved. Converting non-trivial indexes to Awkward structures is more straightforward than the reverse.

The best way to start would be to open a feature-request issue and propose some translation rules with examples: "If given a DataFrame like X, we should make an Awkward Array like Y," which we can talk over before implementation. I have some ideas to start:

   * Converting Pandas column types to Awkward types is a completely independent problem from handling indexes.
   * If the DataFrame has a RangeIndex, the columns can simply be wrapped by a [RecordArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.RecordArray.html).
   * If the DataFrame has an Int64Index, the above should be wrapped in an [IndexedOptionArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.IndexedOptionArray.html) to arrange the order such that `ak_array[i] == df.loc[i]`, and any missing values can be None (`-1` in the `index`).
   * If the DataFrame has a MultiIndex, the above can be wrapped in layers of [ListOffsetArray](https://awkward-array.readthedocs.io/en/latest/ak.layout.ListOffsetArray.html), one for each MultiIndex level.
   * String-valued and datetime-valued indexes would simply have to become columns, since Awkward arrays can't be indexed by anything other than integers.

The complexity of this project is progressive; if you find you need to stop after RangeIndex or something, that would already be valuable and completing the index types would be a matter of layering on top of what you've done.

Thanks!

**Comment by drahnreb** [comment]
I just tried this with a dateset and `0.2.33` and I am still getting a `ValueError: in IndexedArray32 attempting to get 100, index[i] >= len(content)` on a categorical field when doing the following:
```python
array = ak.from_arrow(table)
ak.to_parquet(array, 'tmp.parquet')
rec = ak.from_parquet('tmp.parquet')
```
where `array` is valid and the arrow `table` consists of:
```python
>>> table
pyarrow.Table
label: dictionary<values=string, indices=int32, ordered=0>
```
I think I need to rebuild the categorical as you described as the data seems to be corrupt already. Rebuilding it manually will fix any side effects/corruptions of the data introduced by ARROW-9801.

I will have a look into it later again 

Eventhough `array.label` seems to be consistent data and doesn't seem to be corrupted as it's nested. So at least not before masking/slicing. The indexes do not make sense (at least to me; `len(array) == 1023`): 
```python
>>> array.label.layout
<IndexedArray64>
    <parameters>
        <param key="__array__">"categorical"</param>
    </parameters>
    <index><Index64 i="[0 0 1 0 0 ... 24 24 24 24 24]" offset="0" length="1023" at="0x55a45da19470"/></index>
    <content><IndexedOptionArray64>
        <index><Index64 i="[0 1 2 3 4 ... 21 22 23 24 25]" offset="0" length="26" at="0x55a45da18270"/></index>
        <content><ListArray64>
            <parameters>
                <param key="__array__">"string"</param>
            </parameters>
            <starts><Index64 i="[0 2 5 7 10 ... 52 55 57 60 62]" offset="0" length="26" at="0x55a451197eb0"/></starts>
            <stops><Index64 i="[2 5 7 10 12 ... 55 57 60 62 65]" offset="0" length="26" at="0x55a459bdfb70"/></stops>
            <content><NumpyArray format="B" shape="65" data="79 75 78 79 75 ... 79 75 78 79 75" at="0x55a45dc4bd80">
                <parameters>
                    <param key="__array__">"char"</param>
                </parameters>
            </NumpyArray></content>
        </ListArray64></content>
    </IndexedOptionArray64></content>
</IndexedArray64>
```
I guess #404 would catch that.

**Comment by drahnreb** [comment]
Ok, a manual categorical fixed it.
So this can serve as a workaround (_before_ any data manipulation) for corrupted arrow/parquet data, until [ARROW-9801](https://issues.apache.org/jira/browse/ARROW-9801) is fixed:
```python
fixed_array = ak.with_field(array, manual_categorical, where='label')
```

(_as long as the content is consistent and categorical indexes are just incomplete but not completely corrupted_)

**Comment by jpivarski** [comment]
Yes, this doesn't fix any files created before the bug fix because it was a writing bug, but a reading bug.

I don't know why the above workaround works—I'd have to think more about it. It would be better to generate new files if possible—that works make it easier to know what's going on.
